<a href="https://colab.research.google.com/github/gkianfar/1234llm/blob/main/LLM_promptEngineering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!git clone https://github.com/jamal94sm/TIHM.git
%cd /content/TIHM

Cloning into 'TIHM'...
remote: Enumerating objects: 111, done.
remote: Counting objects: 100% (111/111), done.
remote: Compressing objects: 100% (106/106), done.
remote: Total 111 (delta 40), reused 12 (delta 3), pack-reused 0 (from 0)
Receiving objects: 100% (111/111), 28.08 MiB | 4.42 MiB/s, done.
Resolving deltas: 100% (40/40), done.
Updating files: 100% (27/27), done.
/content/TIHM

In [3]:
pip install -U bitsandbytes

Collecting bitsandbytes
  Downloading bitsandbytes-0.45.5-py3-none-manylinux_2_24_x86_64.whl.metadata (5.0 kB)
Requirement already satisfied: torch<3,>=2.0 in /usr/local/lib/python3.11/dist-packages (from bitsandbytes) (2.6.0+cu124)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from bitsandbytes) (2.0.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from torch<3,>=2.0->bitsandbytes) (3.18.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.11/dist-packages (from torch<3,>=2.0->bitsandbytes) (4.13.2)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch<3,>=2.0->bitsandbytes) (3.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch<3,>=2.0->bitsandbytes) (3.1.6)
Requirement already satisfied: fsspec in /usr/local/lib/python3.11/dist-packages (from torch<3,>=2.0->bitsandbytes) (2025.3.2)
Collecting nvidia-cuda-nvrtc-cu12==12.4.127 (from torch<3,>=2.0->bitsandbytes)
  Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.4.127 (from torch<3,>=2.0->bitsandbytes)
  Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.4.127 (from torch<3,>=2.0->bitsandbytes)
  Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==9.1.0.70 (from torch<3,>=2.0->bitsandbytes)
  Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.4.5.8 (from torch<3,>=2.0->bitsandbytes)
  Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.2.1.3 (from torch<3,>=2.0->bitsandbytes)
  Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.5.147 (from torch<3,>=2.0->bitsandbytes)
  Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.6.1.9 (from torch<3,>=2.0->bitsandbytes)
  Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.3.1.170 (from torch<3,>=2.0->bitsandbytes)
  Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.11/dist-packages (from torch<3,>=2.0->bitsandbytes) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch<3,>=2.0->bitsandbytes) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch<3,>=2.0->bitsandbytes) (12.4.127)
Collecting nvidia-nvjitlink-cu12==12.4.127 (from torch<3,>=2.0->bitsandbytes)
  Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.11/dist-packages (from torch<3,>=2.0->bitsandbytes) (3.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch<3,>=2.0->bitsandbytes) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch<3,>=2.0->bitsandbytes) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch<3,>=2.0->bitsandbytes) (3.0.2)
Downloading bitsandbytes-0.45.5-py3-none-manylinux_2_24_x86_64.whl (76.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.1/76.1 MB 10.9 MB/s eta 0:00:00
Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl (363.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 4.4 MB/s eta 0:00:00
Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (13.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 101.0 MB/s eta 0:00:00
Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (24.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 71.9 MB/s eta 0:00:00
Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (883 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 48.8 MB/s eta 0:00:00
Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl (664.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 2.1 MB/s eta 0:00:00
Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl (211.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 5.1 MB/s eta 0:00:00
Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl (56.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 11.4 MB/s eta 0:00:00
Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl (127.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 7.4 MB/s eta 0:00:00
Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl (207.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 5.8 MB/s eta 0:00:00
Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (21.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 88.8 MB/s eta 0:00:00
Installing collected packages: nvidia-nvjitlink-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, nvidia-cusparse-cu12, nvidia-cudnn-cu12, nvidia-cusolver-cu12, bitsandbytes
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstalling nvidia-nvjitlink-cu12-12.5.82:
      Successfully uninstalled nvidia-nvjitlink-cu12-12.5.82
  Attempting uninstall: nvidia-curand-cu12
    Found existing installation: nvidia-curand-cu12 10.3.6.82
    Uninstalling nvidia-curand-cu12-10.3.6.82:
      Successfully uninstalled nvidia-curand-cu12-10.3.6.82
  Attempting uninstall: nvidia-cufft-cu12
    Found existing installation: nvidia-cufft-cu12 11.2.3.61
    Uninstalling nvidia-cufft-cu12-11.2.3.61:
      Successfully uninstalled nvidia-cufft-cu12-11.2.3.61
  Attempting uninstall: nvidia-cuda-runtime-cu12
    Found existing installation: nvidia-cuda-runtime-cu12 12.5.82
    Uninstalling nvidia-cuda-runtime-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-runtime-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-nvrtc-cu12
    Found existing installation: nvidia-cuda-nvrtc-cu12 12.5.82
    Uninstalling nvidia-cuda-nvrtc-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-nvrtc-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-cupti-cu12
    Found existing installation: nvidia-cuda-cupti-cu12 12.5.82
    Uninstalling nvidia-cuda-cupti-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-cupti-cu12-12.5.82
  Attempting uninstall: nvidia-cublas-cu12
    Found existing installation: nvidia-cublas-cu12 12.5.3.2
    Uninstalling nvidia-cublas-cu12-12.5.3.2:
      Successfully uninstalled nvidia-cublas-cu12-12.5.3.2
  Attempting uninstall: nvidia-cusparse-cu12
    Found existing installation: nvidia-cusparse-cu12 12.5.1.3
    Uninstalling nvidia-cusparse-cu12-12.5.1.3:
      Successfully uninstalled nvidia-cusparse-cu12-12.5.1.3
  Attempting uninstall: nvidia-cudnn-cu12
    Found existing installation: nvidia-cudnn-cu12 9.3.0.75
    Uninstalling nvidia-cudnn-cu12-9.3.0.75:
      Successfully uninstalled nvidia-cudnn-cu12-9.3.0.75
  Attempting uninstall: nvidia-cusolver-cu12
    Found existing installation: nvidia-cusolver-cu12 11.6.3.83
    Uninstalling nvidia-cusolver-cu12-11.6.3.83:
      Successfully uninstalled nvidia-cusolver-cu12-11.6.3.83
Successfully installed bitsandbytes-0.45.5 nvidia-cublas-cu12-12.4.5.8 nvidia-cuda-cupti-cu12-12.4.127 nvidia-cuda-nvrtc-cu12-12.4.127 nvidia-cuda-runtime-cu12-12.4.127 nvidia-cudnn-cu12-9.1.0.70 nvidia-cufft-cu12-11.2.1.3 nvidia-curand-cu12-10.3.5.147 nvidia-cusolver-cu12-11.6.1.9 nvidia-cusparse-cu12-12.3.1.170 nvidia-nvjitlink-cu12-12.4.127

In [4]:
pip install --upgrade sympy

Requirement already satisfied: sympy in /usr/local/lib/python3.11/dist-packages (1.13.1)
Collecting sympy
  Downloading sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy) (1.3.0)
Downloading sympy-1.14.0-py3-none-any.whl (6.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 50.5 MB/s eta 0:00:00
Installing collected packages: sympy
  Attempting uninstall: sympy
    Found existing installation: sympy 1.13.1
    Uninstalling sympy-1.13.1:
      Successfully uninstalled sympy-1.13.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torch 2.6.0+cu124 requires sympy==1.13.1; python_version >= "3.9", but you have sympy 1.14.0 which is incompatible.
Successfully installed sympy-1.14.0

In [5]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from matplotlib import cm
import matplotlib.patches as mpatches
from collections.abc import Iterable
from sklearn.preprocessing import StandardScaler
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import os
import warnings
warnings.filterwarnings('ignore')
from matplotlib import cm
#from utils import *

%matplotlib inline
## Set colour palette
ibm_colorblind = ['#648FFF', '#FE6100', '#DC267F', '#785EF0', '#FFB000','#48A9A6']
sns.set_palette(ibm_colorblind)

**Functions**

In [6]:
def correct_col_type(df,col):
    raw_type = str(type(df[col].dtype)).split('.')[-1].split('\'')[0].lower()
    #print(col,raw_type)
    if 'object' in raw_type:
        if 'date' in col or 'timestamp' in col or 'datetime' in col:
            return pd.to_datetime(df[col])
        else:
            return df[col].astype('category')
    else:
        return df[col]


def gen_date_col(df, tcol):
    df['timestamp'] = pd.to_datetime(df['timestamp'])
    df['date'] = df[tcol].dt.date
    return df

**Set Data and Fig folders paths**

In [7]:
## Please change the path with the path of your dataset
DPATH = './Dataset'
SAVE_PATH = './Figs/'
if not os.path.exists(SAVE_PATH):
    os.makedirs(SAVE_PATH)

**Import Files**

In [8]:
### Demographics
f = 'Demographics.csv'
fpth = os.path.join(DPATH,f)
demographics_df = pd.read_csv(fpth)
for col in demographics_df.columns:
    demographics_df[col] = correct_col_type(demographics_df,col)


demographics_df

   patient_id        age     sex
0       b9d58   (70, 80]  Female
1       c55f8   (80, 90]  Female
2       16f4b   (80, 90]    Male
3       fd100  (90, 110]  Female
4       1fbe4   (80, 90]    Male
5       a539e   (80, 90]    Male
6       d263a   (70, 80]  Female
7       0d5ef   (70, 80]    Male
8       93c14   (70, 80]    Male
9       7db78  (90, 110]    Male
10      a380e   (70, 80]    Male
11      2f54b   (80, 90]  Female
12      d93d8   (70, 80]  Female
13      ec812   (70, 80]    Male
14      ca44d   (80, 90]  Female
15      e87bd  (90, 110]  Female
16      0cda9   (70, 80]  Female
17      96adf   (70, 80]  Female
18      55cd4  (90, 110]    Male
19      b45c2  (90, 110]    Male
20      0efe8   (70, 80]  Female
21      eca1f  (90, 110]    Male
22      d44d2  (90, 110]  Female
23      95899   (70, 80]    Male
24      56b6b   (70, 80]  Female
25      c5785  (90, 110]  Female
26      76230   (80, 90]    Male
27      30a32   (70, 80]  Female
28      714d7   (80, 90]    Male
29      201d8  (90, 110]    Male
30      8a835   (80, 90]  Female
31      6b29b   (80, 90]    Male
32      d8d97   (80, 90]    Male
33      65db4  (90, 110]  Female
34      73f7c   (70, 80]    Male
35      099bc   (80, 90]  Female
36      ab47a  (90, 110]  Female
37      28710   (80, 90]    Male
38      3fb61   (80, 90]    Male
39      c5031   (80, 90]  Female
40      c8574   (70, 80]    Male
41      8d0d4   (80, 90]  Female
42      393cb   (80, 90]    Male
43      46286   (70, 80]    Male
44      a2849   (80, 90]    Male
45      e4959  (90, 110]  Female
46      e8a78   (80, 90]  Female
47      f220c  (90, 110]  Female
48      561af   (80, 90]  Female
49      0697d   (80, 90]    Male
50      e2472   (80, 90]    Male
51      385de   (70, 80]  Female
52      d7a46   (80, 90]  Female
53      2b131   (80, 90]  Female
54      0f352   (80, 90]    Male
55      b0455   (80, 90]    Male

In [9]:
### Labels
f = 'Labels.csv'
fpth = os.path.join(DPATH,f)
labels_df = pd.read_csv(fpth)
for col in labels_df.columns:
    labels_df[col] = correct_col_type(labels_df,col)
if 'date' in labels_df.columns:
    labels_df = labels_df.rename(columns={'date':'timestamp'})
if 'type' in labels_df.columns:
    labels_df = labels_df.rename(columns={'type':'label'})
labels_df = gen_date_col(labels_df,tcol='timestamp')

labels_patients = np.unique(labels_df['patient_id'])

In [10]:
agit_df = labels_df[labels_df['label'] == 'Agitation']
agit_df

    patient_id           timestamp      label        date
2        16f4b 2019-04-11 12:00:22  Agitation  2019-04-11
4        16f4b 2019-04-14 12:00:07  Agitation  2019-04-14
5        16f4b 2019-04-15 18:00:24  Agitation  2019-04-15
6        16f4b 2019-04-16 18:00:38  Agitation  2019-04-16
11       16f4b 2019-04-21 12:00:55  Agitation  2019-04-21
..         ...                 ...        ...         ...
587      0d5ef 2019-06-28 18:02:11  Agitation  2019-06-28
588      d7a46 2019-06-28 18:02:21  Agitation  2019-06-28
598      6b29b 2019-06-29 12:00:27  Agitation  2019-06-29
599      95899 2019-06-29 12:01:20  Agitation  2019-06-29
604      95899 2019-06-29 18:01:14  Agitation  2019-06-29

[135 rows x 4 columns]

In [11]:
### Physiology
f = 'Physiology.csv'
fpth = os.path.join(DPATH,f)
df = pd.read_csv(fpth)
for col in df.columns:
    df[col] = correct_col_type(df,col)
if 'date' in df.columns:
    physiology_df = df.rename(columns={'date':'timestamp'})
physiology_df = gen_date_col(physiology_df,tcol='timestamp')

physiology_patients = np.unique(df['patient_id'])
physiology_parameters = np.unique(df['device_type']).tolist()

#physiology_df

In [12]:
# Get the unique patient IDs and device types
patients = physiology_df['patient_id'].unique()
device_types = physiology_df['device_type'].unique()

# Create a DataFrame that retains original study days for each patient
study_days = physiology_df[['patient_id', 'date']].drop_duplicates()

# Prepare a list to hold the filled results
filled_results_list = []

# Iterate over each patient
for patient in patients:
    # Get the patient's data
    patient_data = physiology_df[physiology_df['patient_id'] == patient]

    # For each study day, check measurements
    for date in study_days[study_days['patient_id'] == patient]['date']:
        for device in device_types:
            # Get all values for this patient, date, and device type
            values = patient_data.loc[(patient_data['date'] == date) & (patient_data['device_type'] == device), 'value']
            if not values.empty:
                # Compute the average value (considering repetitions)
                avg_value = values.mean()
                unit = patient_data.loc[(patient_data['date'] == date) & (patient_data['device_type'] == device), 'unit'].values[0]
                filled_results_list.append({
                    'patient_id': patient,
                    'date': date,
                    'device_type': device,
                    'value': avg_value,
                    'unit': unit
                })
            else:
                # If there are no measurements, append a None
                filled_results_list.append({
                    'patient_id': patient,
                    'date': date,
                    'device_type': device,
                    'value': None,  # To be filled later
                    'unit': None
                })

# Convert the list of dictionaries to a DataFrame
filled_results = pd.DataFrame(filled_results_list)

# Now, we can fill in the missing values
def fill_missing_values(group):
    for device in device_types:
        # Patient's specific values for this device
        patient_values = group[group['device_type'] == device]['value']

        # If any values exist, calculate the average to fill
        if patient_values.notnull().any():
            avg_patient_value = patient_values.mean()
            group.loc[(group['device_type'] == device) & (group['value'].isnull()), 'value'] = avg_patient_value
        else:
            # If no values exist at all, use the overall average for this device if applicable
            if physiology_df[physiology_df['device_type'] == device]['value'].notna().any():
                overall_avg = physiology_df[physiology_df['device_type'] == device]['value'].mean()
                group.loc[(group['device_type'] == device) & (group['value'].isnull()), 'value'] = overall_avg

    return group

# Apply filling logic to the filled_results DataFrame
filled_physiology_df = filled_results.groupby('patient_id', group_keys=False).apply(fill_missing_values)

# Sort by patient_id and date
filled_physiology_df.sort_values(by=['patient_id', 'date'], inplace=True)

In [13]:
physiology_df = filled_physiology_df
physiology_df

      patient_id        date               device_type       value       unit
0          0697d  2019-06-28          Body Temperature   36.186400        Cel
1          0697d  2019-06-28   Systolic blood pressure  165.000000     mm[Hg]
2          0697d  2019-06-28  Diastolic blood pressure   82.000000     mm[Hg]
3          0697d  2019-06-28                Heart rate   42.000000  beats/min
4          0697d  2019-06-28               Body weight   86.300000         kg
...          ...         ...                       ...         ...        ...
17275      fd100  2019-06-29                Heart rate   57.500000       None
17276      fd100  2019-06-29               Body weight   55.800000       None
17277      fd100  2019-06-29         O/E - muscle mass   37.500000       None
17278      fd100  2019-06-29          Total body water   48.700000       None
17279      fd100  2019-06-29          Skin Temperature   34.151209       None

[17280 rows x 5 columns]

# **Activity**

In [14]:
### Activity

f = 'Activity.csv'
fpth = os.path.join(DPATH,f)
df = pd.read_csv(fpth)
for col in df.columns:
    df[col] = correct_col_type(df,col)
if 'date' in df.columns:
    activity_df = df.rename(columns={'date':'timestamp'})
    activity_df['timestamp'] = pd.to_datetime(activity_df['timestamp'])
    activity_df['date'] = activity_df['timestamp'].dt.date
    activity_df['time'] = activity_df['timestamp'].dt.time


activity_patients = np.unique(activity_df['patient_id'])

activity_df

        patient_id location_name           timestamp        date      time
0            0697d   Fridge Door 2019-06-28 13:03:29  2019-06-28  13:03:29
1            0697d       Kitchen 2019-06-28 13:11:44  2019-06-28  13:11:44
2            0697d    Front Door 2019-06-28 13:13:50  2019-06-28  13:13:50
3            0697d       Bedroom 2019-06-28 13:13:53  2019-06-28  13:13:53
4            0697d   Fridge Door 2019-06-28 13:14:09  2019-06-28  13:14:09
...            ...           ...                 ...         ...       ...
1030554      fd100       Hallway 2019-06-30 23:48:50  2019-06-30  23:48:50
1030555      fd100        Lounge 2019-06-30 23:49:40  2019-06-30  23:49:40
1030556      fd100       Kitchen 2019-06-30 23:50:02  2019-06-30  23:50:02
1030557      fd100    Front Door 2019-06-30 23:51:28  2019-06-30  23:51:28
1030558      fd100    Front Door 2019-06-30 23:51:36  2019-06-30  23:51:36

[1030559 rows x 5 columns]

In [15]:
def label_outside_all_patients(activity_df, threshold_minutes=2):
    """
    Labels 'Outside' events between successive 'Front Door' and 'Back Door' events
    for all patients and all days in the dataset.
    - Marks both the **start** and **end** of the outside event.
    - Inserts "Outside" events at regular intervals.
    """
    activity_df['timestamp'] = pd.to_datetime(activity_df['timestamp'])  # Ensure datetime format
    activity_df = activity_df.sort_values(by=['patient_id', 'date', 'timestamp'])  # Sort by patient, day, time

    # Container for processed data
    new_data = []

    # Process each patient separately
    for patient_id, patient_group in activity_df.groupby('patient_id'):
        for date, day_group in patient_group.groupby('date'):
            day_group = day_group.sort_values(by='timestamp').reset_index(drop=True)  # Ensure sorted order

            new_rows = []
            for i in range(len(day_group) - 1):
                current_row = day_group.iloc[i]
                next_row = day_group.iloc[i + 1]
                current_time = current_row['timestamp']
                next_time = next_row['timestamp']

                # Check if the time difference exceeds the threshold
                if (next_time - current_time).total_seconds() / 60.0 > threshold_minutes:
                    if (current_row['location_name'] in ['Front Door', 'Back Door']) and \
                       (next_row['location_name'] in ['Front Door', 'Back Door']):

                        # Mark the start of the "Outside" event
                        start_outside = current_row.copy()
                        start_outside['location_name'] = 'Outside'
                        new_rows.append(start_outside)

                        # Insert 'Outside' events at regular intervals
                        temp_time = current_time
                        while (next_time - temp_time).total_seconds() / 60.0 > threshold_minutes:
                            temp_time += pd.Timedelta(minutes=threshold_minutes)
                            if temp_time >= next_time:
                                break
                            new_row = current_row.copy()
                            new_row['timestamp'] = temp_time
                            new_row['location_name'] = 'Outside'
                            new_rows.append(new_row)

                        # Mark the end of the "Outside" event
                        end_outside = next_row.copy()
                        end_outside['location_name'] = 'Outside'
                        new_rows.append(end_outside)

            # Append the modified day_group with new "Outside" events
            new_data.append(pd.concat([day_group, pd.DataFrame(new_rows)], ignore_index=True)
                            .sort_values(by='timestamp').reset_index(drop=True))

    # Combine all processed patient data
    updated_activity_df = pd.concat(new_data, ignore_index=True)

    return updated_activity_df

# Example usage
updated_activity_df = label_outside_all_patients(activity_df)

In [16]:

def calculate_mobility_outside_and_location_counts(activity_df):
    """
    Computes:
    - 'Mobility': The number of location transitions per day.
    - 'Outside Time': The total time (in minutes) a patient spent outside per day.
    - Frequency count for each location type (e.g., Bedroom, Kitchen, Lounge).
    """
    # Ensure timestamps are in datetime format
    activity_df['timestamp'] = pd.to_datetime(activity_df['timestamp'])

    # Sort data by patient, date, and time
    activity_df = activity_df.sort_values(by=['patient_id', 'date', 'timestamp'])

    # Remove NaN values from the 'location_name' column
    activity_df = activity_df.dropna(subset=['location_name'])

    # Identify if the location is outside (Front Door or Back Door)
    activity_df['outside'] = activity_df['location_name'].isin(['Front Door', 'Back Door'])

    # Get all unique indoor locations (excluding Front Door & Back Door)
    indoor_locations = sorted(set(activity_df['location_name']) - {'Front Door', 'Back Door'})

    # Create an empty list to store results
    feature_results = []

    # Process each patient separately
    for patient_id, patient_group in activity_df.groupby('patient_id'):
        # Get unique study days for this patient (only days with activity)
        study_days = patient_group['date'].unique()

        # Process each study day
        for study_day in study_days:
            # Get activity data for this specific day
            day_data = patient_group[patient_group['date'] == study_day].copy()

            # Extract location sequence
            location_sequence = day_data['location_name'].values

            # Compute mobility: Count location transitions
            mobility_count = np.sum(np.array(location_sequence[1:]) != np.array(location_sequence[:-1])) if len(location_sequence) > 1 else 0

            # Compute outside time
            total_time_outside = 0
            for i in range(1, len(day_data)):
                if day_data['outside'].iloc[i] and day_data['outside'].iloc[i - 1]:
                    time_diff = (day_data['timestamp'].iloc[i] - day_data['timestamp'].iloc[i - 1]).total_seconds() / 60
                    total_time_outside += time_diff

            # Count occurrences of each indoor location
            location_counts = {f"{loc}_count": (day_data['location_name'] == loc).sum() for loc in indoor_locations}

            # Store result
            result_entry = {
                'patient_id': patient_id,
                'date': study_day,
                'location_change_count': mobility_count,
                'outside_time': round(total_time_outside, 2)  # Round to 2 decimal places
            }
            result_entry.update(location_counts)  # Add location counts dynamically

            feature_results.append(result_entry)

    # Convert results into a DataFrame
    activity_features_df = pd.DataFrame(feature_results)

    return activity_features_df

# Example usage
activity_features_df = calculate_mobility_outside_and_location_counts(activity_df)
print(activity_features_df)

     patient_id        date  location_change_count  outside_time  \
0         0697d  2019-06-28                    216         27.70
1         0697d  2019-06-29                    221        128.33
2         0697d  2019-06-30                    220        171.98
3         099bc  2019-05-15                    116        141.58
4         099bc  2019-05-16                    186        166.62
...         ...         ...                    ...           ...
2717      f220c  2019-06-30                     74          4.08
2718      fd100  2019-06-27                    265        157.92
2719      fd100  2019-06-28                    339         38.10
2720      fd100  2019-06-29                    297          3.48
2721      fd100  2019-06-30                    272          3.75

      Bathroom_count  Bedroom_count  Fridge Door_count  Hallway_count  \
0                  7             24                 23             40
1                 11             26                  8             57
2                 14             53                  0             57
3                 17             31                 27             32
4                 42             85                 22             50
...              ...            ...                ...            ...
2717              12             61                 24             32
2718              24             48                 23             47
2719              32             91                  7             58
2720              33             56                 27             61
2721              27             86                  8             43

      Kitchen_count  Lounge_count
0               106            80
1               120           117
2               119           103
3                71             6
4               104             9
...             ...           ...
2717              0             0
2718            100            97
2719            145           120
2720            110            96
2721            120           110

[2722 rows x 10 columns]

# text prompt generation

In [17]:
ag_df = agit_df[['patient_id','date']].drop_duplicates()
agit_days = {}
stats = {}
feature_columns = activity_features_df.columns

for pid in ag_df.patient_id.unique():
  agit_days[pid] = ag_df[ag_df['patient_id']==pid].date.tolist()
  pid_stats = {}
  for col in feature_columns:
    if pd.api.types.is_numeric_dtype(activity_features_df[col]):
      pid_stats[col] = round(activity_features_df[col][(activity_features_df['patient_id'] == pid) & (~activity_features_df['date'].isin(agit_days[pid]))].mean())
  stats[pid] = pid_stats
stats[pid]

{'location_change_count': 255,
 'outside_time': 15,
 'Bathroom_count': 48,
 'Bedroom_count': 42,
 'Fridge Door_count': 52,
 'Hallway_count': 13,
 'Kitchen_count': 84,
 'Lounge_count': 127}

In [18]:
def generate_balanced_text_prompts(demographics_df, agit_df, physiology_df, activity_features_df, stats=None):
    """
    Generates structured text prompts for each patient-day using available data.
    Ensures:
    - Uses all available agitated samples
    - Dynamically adjusts the number of normal samples
    - Splits into exactly 250 training samples and 20 test samples (10 Agitated, 10 Normal)
    - Stores test labels for evaluation
    """

    # Convert agitation events into a dictionary for fast lookup
    agit_dict = {(row['patient_id'], row['date']): "Agitated" for _, row in agit_df.iterrows()}

    # Convert demographics into a dictionary for fast lookup
    demographics_dict = demographics_df.set_index('patient_id').to_dict(orient='index')

    # Convert physiology into a dictionary with patient_id & date as keys
    physiology_dict = physiology_df.pivot(index=['patient_id', 'date'], columns='device_type', values='value').to_dict(orient='index')

    # Identify all agitated samples
    agitated_samples = activity_features_df[activity_features_df.apply(lambda row: (row['patient_id'], row['date']) in agit_dict, axis=1)]
    num_agitated = len(agitated_samples)

    # Identify all normal samples (excluding agitated ones)
    normal_samples = activity_features_df[~activity_features_df.apply(lambda row: (row['patient_id'], row['date']) in agit_dict, axis=1)]
    num_normal = len(normal_samples)

    # Adjust selection dynamically
    normal_train_count = min(125, num_normal - 10)  # Ensure at least 10 remain for testing
    normal_test_count = min(10, num_normal - normal_train_count)  # Ensure test is max 10

    agitated_train_count = min(125, num_agitated - 10)  # Ensure at least 10 remain for testing
    agitated_test_count = min(10, num_agitated - agitated_train_count)

    # Select samples dynamically
    train_agitated = agitated_samples.sample(n=agitated_train_count, random_state=42)
    test_agitated = agitated_samples.drop(train_agitated.index).sample(n=agitated_test_count, random_state=42)

    train_normal = normal_samples.sample(n=normal_train_count, random_state=42)
    test_normal = normal_samples.drop(train_normal.index).sample(n=normal_test_count, random_state=42)

    # **Final Dataset Splits**
    train_data = pd.concat([train_agitated, train_normal]).sample(frac=1, random_state=42)  # Shuffle
    test_data = pd.concat([test_agitated, test_normal]).sample(frac=1, random_state=42)  # Shuffle

    # Prepare lists for train and test samples
    train_samples = []
    test_samples = []
    test_labels = []  # Store true labels of test samples

    # Process each patient-day in train and test sets
    for split, dataset, sample_list, mask_label, label_list in zip(
        ["Train", "Test"],
        [train_data, test_data],
        [train_samples, test_samples],
        ["{LABEL}", "[MASK]"],
        [None, test_labels]  # Only store labels for test samples
    ):
        for _, row in dataset.iterrows():
            patient_id = row['patient_id']
            date = row['date']

            # Retrieve demographic information
            demographic_info = demographics_dict.get(patient_id, {})
            age_group = demographic_info.get('age', "Unknown Age Group")
            gender = demographic_info.get('sex', "Unknown Gender")

            # Determine agitation status
            agitation_label = agit_dict.get((patient_id, date), "Normal")

            # Retrieve physiological data for the day
            physiology_data = physiology_dict.get((patient_id, date), {})
            physiology_text = "\n".join([f"- {k}: {round(v, 2)}" for k, v in physiology_data.items() if pd.notna(v)])

            # Retrieve activity features
            location_change_count = row['location_change_count']
            outside_time = row['outside_time']

            # Extract only valid location counts (excluding "location_change_count" itself)
            location_columns = [col for col in activity_features_df.columns if col.endswith('_count') and col != "location_change_count"]
            location_counts = "\n".join([f"- {col.replace('_count', ' Count')}: {row[col]}" for col in location_columns])

            # Construct structured text prompt
            text_prompt = f"""
            - **Age Group**: {age_group}
            - **Gender**: {gender}
            ---------------------
            - **Physiological Data**:
            {physiology_text if physiology_text else "- No physiological data available"}
            ---------------------
            - **Activity Information**:
            - Location Change Count: {location_change_count}
            - Time Spent Outside: {outside_time} min
            {location_counts}
            ---------------------
            Label: {mask_label}
            """
            # Prompt for stats
            if stats is not None:
              stats_prompt = "Average of features over normal days:\n"

              if patient_id in stats:
                for k,v in stats[patient_id].items():
                  stats_prompt += f"- {k}: {v}\n"
                stats_prompt+="---------------------\n"
              else:
                stats_prompt +="No prior stats available for this patient.\n"
              text_prompt = stats_prompt + text_prompt


            # Remove excessive spaces for formatting
            text_prompt = "\n".join([line.strip() for line in text_prompt.split("\n") if line.strip()])

            # Add the structured text to the respective list
            if split == "Train":
                sample_list.append(text_prompt.replace("{LABEL}", agitation_label))  # Replace {LABEL} in train
            else:
                sample_list.append(text_prompt)  # Test samples keep "[MASK]"
                label_list.append(agitation_label)  # Store true label for evaluation

    return train_samples, test_samples, test_labels


# Example usage:
train_samples, test_samples, test_labels = generate_balanced_text_prompts(demographics_df,
                            agit_df, physiology_df, activity_features_df,stats)

# Verify correct train-test split
print(f"Train Samples: {len(train_samples)} (Expected: 250 or max possible)")
print(f"Test Samples: {len(test_samples)} (Expected: 20 or max possible)")
print(f"Stored Test Labels: {len(test_labels)} (should match test samples)")

# Display sample outputs
print("\n===== TRAIN SAMPLE (with embedded labels) =====")
print(train_samples[0])  # Properly formatted for zero-shot inference

print("\n===== TEST SAMPLE (without labels) =====")
print(test_samples[0])  # Testing samples don't have a label

print("\n===== TEST LABELS (Stored for Evaluation) =====")
print(test_labels[:])  # Show a few stored true labels

Train Samples: 229 (Expected: 250 or max possible)
Test Samples: 20 (Expected: 20 or max possible)
Stored Test Labels: 20 (should match test samples)

===== TRAIN SAMPLE (with embedded labels) =====
Average of features over normal days:
- location_change_count: 155
- outside_time: 158
- Bathroom_count: 44
- Bedroom_count: 74
- Fridge Door_count: 21
- Hallway_count: 40
- Kitchen_count: 68
- Lounge_count: 5
---------------------
- **Age Group**: (80, 90]
- **Gender**: Female
---------------------
- **Physiological Data**:
- Body Temperature: 37.15
- Body weight: 52.0
- Diastolic blood pressure: 83.5
- Heart rate: 70.5
- O/E - muscle mass: 37.14
- Skin Temperature: 34.15
- Systolic blood pressure: 137.0
- Total body water: 51.5
---------------------
- **Activity Information**:
- Location Change Count: 163
- Time Spent Outside: 173.12 min
- Bathroom Count: 39
- Bedroom Count: 95
- Fridge Door Count: 12
- Hallway Count: 45
- Kitchen Count: 58
- Lounge Count: 5
---------------------
Label: Normal

===== TEST SAMPLE (without labels) =====
Average of features over normal days:
- location_change_count: 234
- outside_time: 232
- Bathroom_count: 27
- Bedroom_count: 28
- Fridge Door_count: 59
- Hallway_count: 67
- Kitchen_count: 82
- Lounge_count: 50
---------------------
- **Age Group**: (90, 110]
- **Gender**: Female
---------------------
- **Physiological Data**:
- Body Temperature: 36.16
- Body weight: 53.8
- Diastolic blood pressure: 71.0
- Heart rate: 78.0
- O/E - muscle mass: 36.9
- Skin Temperature: 34.15
- Systolic blood pressure: 132.0
- Total body water: 49.7
---------------------
- **Activity Information**:
- Location Change Count: 286
- Time Spent Outside: 278.25 min
- Bathroom Count: 44
- Bedroom Count: 37
- Fridge Door Count: 56
- Hallway Count: 77
- Kitchen Count: 78
- Lounge Count: 58
---------------------
Label: [MASK]

===== TEST LABELS (Stored for Evaluation) =====
['Agitated', 'Normal', 'Normal', 'Agitated', 'Agitated', 'Agitated', 'Normal', 'Agitated', 'Normal', 'Normal', 'Normal', 'Agitated', 'Agitated', 'Normal', 'Agitated', 'Normal', 'Agitated', 'Normal', 'Normal', 'Agitated']

In [19]:
def get_few_shot_prompt(example_prompts_list, question_prompt, question=None, context=None, instruction=None, knowledge=None,
                        INSTRUCTION_LABEL='Instruction: ',
                        CONTEXT_LABEL='Context: ',
                        QUESTION_LABEL='Question: ',
                        ):
    """
    Constructs a few-shot learning prompt.

    Parameters:
    - example_prompts_list: List of example prompts used for in-context learning.
    - question_prompt: A prompt without an answer.
    - question: (Optional) A separate question to be included.
    - instruction: (Optional) Additional instruction.
    - knowledge: (Optional) Additional background knowledge.
    """
    few_shot_prompt = ""

    if instruction:
      few_shot_prompt = INSTRUCTION_LABEL + instruction + "\n\n"

    # Add context information
    if context:
      few_shot_prompt += CONTEXT_LABEL + context + "\n\n"

    # Construct few-shot examples
    if example_prompts_list:
      few_shot_prompt += "\n\n".join([f"Example {i}:\n{p}" for i, p in enumerate(example_prompts_list)])+ "\n\n"

    # Add question prompts
    if question:
      few_shot_prompt += QUESTION_LABEL + question + "\n"

    few_shot_prompt += question_prompt

    return few_shot_prompt
def get_prompt_label(prompt):
  return prompt.split("\n")[-1].split("Label:")[-1].strip()

In [20]:
# Determine positive and negative sample ids
positive_sample_ids = []
negative_sample_ids = []
for i, sample in enumerate(train_samples):
  if get_prompt_label(sample) == "Agitated":
    positive_sample_ids.append(i)
  else:
    negative_sample_ids.append(i)

print(f"Count of positives:{len(positive_sample_ids)}")
print(f"Count of negative:{len(negative_sample_ids)}")

Count of positives:104
Count of negative:125

In [21]:
## Arrange example and test samples
# Ratio of positive samples
ratio = 0.5
k = 10 # shots
number_pos = int(k*ratio)
number_neg = k - number_pos
train_ids = []

# Set seed for reproducability
seed_id = 2025
np.random.seed(seed_id)
list1 = np.random.choice(positive_sample_ids, number_pos, replace=False)
list2 = np.random.choice(negative_sample_ids, number_neg, replace=False)
for pair in zip(list1,list2):
  train_ids.extend(pair)
example_promts = [train_samples[i] for i in train_ids]

In [27]:
instruction = 'Instruction: First, read and understand the definition of agitation in the context section. Then, analyze the examples to understand patterns that distinguish "Agitated" from "Normal" behavior. When evaluating the final question, compare its features to the examples and reason through which label it aligns with most closely. After the reasoning, predict the label and explain why.'
context= 'Agitation is a state of heightened restlessness or emotional disturbance that can affect both the mind and body. Individuals experiencing agitation may exhibit physical signs such as fidgeting, pacing, or rapid movements. Behaviorally, they might struggle to concentrate, become easily irritable, or engage in excessive talking. Emotionally, agitation often manifests as a feeling of tension or unease, sometimes escalating into hostility or aggression if not addressed. This condition can arise due to various triggers, including stress, anxiety, medical conditions, or external situations. Recognizing and addressing the underlying cause is essential for managing agitation effectively and preventing its escalation.'
question='What is the label for the following input based on the observed examples?[Agitated/Normal]'
few_shot_prompt = get_few_shot_prompt(example_promts, test_samples[19], question=question, context=context, instruction=instruction)
print(few_shot_prompt)

Instruction: Instruction: First, read and understand the definition of agitation in the context section. Then, analyze the examples to understand patterns that distinguish "Agitated" from "Normal" behavior. When evaluating the final question, compare its features to the examples and reason through which label it aligns with most closely. After the reasoning, predict the label and explain why.

Context: Agitation is a state of heightened restlessness or emotional disturbance that can affect both the mind and body. Individuals experiencing agitation may exhibit physical signs such as fidgeting, pacing, or rapid movements. Behaviorally, they might struggle to concentrate, become easily irritable, or engage in excessive talking. Emotionally, agitation often manifests as a feeling of tension or unease, sometimes escalating into hostility or aggression if not addressed. This condition can arise due to various triggers, including stress, anxiety, medical conditions, or external situations. Recognizing and addressing the underlying cause is essential for managing agitation effectively and preventing its escalation.

Example 0:
Average of features over normal days:
- location_change_count: 219
- outside_time: 133
- Bathroom_count: 19
- Bedroom_count: 33
- Fridge Door_count: 43
- Hallway_count: 51
- Kitchen_count: 108
- Lounge_count: 88
---------------------
- **Age Group**: (80, 90]
- **Gender**: Female
---------------------
- **Physiological Data**:
- Body Temperature: 36.4
- Body weight: 74.37
- Diastolic blood pressure: 80.0
- Heart rate: 130.0
- O/E - muscle mass: 40.93
- Skin Temperature: 34.15
- Systolic blood pressure: 177.0
- Total body water: 41.46
---------------------
- **Activity Information**:
- Location Change Count: 517
- Time Spent Outside: 5.03 min
- Bathroom Count: 1
- Bedroom Count: 8
- Fridge Door Count: 70
- Hallway Count: 188
- Kitchen Count: 199
- Lounge Count: 186
---------------------
Label: Agitated

Example 1:
Average of features over normal days:
- location_change_count: 175
- outside_time: 137
- Bathroom_count: 21
- Bedroom_count: 24
- Fridge Door_count: 31
- Hallway_count: 50
- Kitchen_count: 87
- Lounge_count: 39
---------------------
- **Age Group**: (80, 90]
- **Gender**: Male
---------------------
- **Physiological Data**:
- Body Temperature: 36.96
- Body weight: 72.7
- Diastolic blood pressure: 89.0
- Heart rate: 93.0
- O/E - muscle mass: 54.2
- Skin Temperature: 34.15
- Systolic blood pressure: 146.0
- Total body water: 52.3
---------------------
- **Activity Information**:
- Location Change Count: 259
- Time Spent Outside: 80.63 min
- Bathroom Count: 24
- Bedroom Count: 27
- Fridge Door Count: 48
- Hallway Count: 66
- Kitchen Count: 132
- Lounge Count: 52
---------------------
Label: Normal

Example 2:
Average of features over normal days:
- location_change_count: 250
- outside_time: 17
- Bathroom_count: 76
- Bedroom_count: 14
- Fridge Door_count: 0
- Hallway_count: 104
- Kitchen_count: 117
- Lounge_count: 0
---------------------
- **Age Group**: (80, 90]
- **Gender**: Male
---------------------
- **Physiological Data**:
- No physiological data available
---------------------
- **Activity Information**:
- Location Change Count: 420
- Time Spent Outside: 2.4 min
- Bathroom Count: 137
- Bedroom Count: 76
- Fridge Door Count: 0
- Hallway Count: 152
- Kitchen Count: 172
- Lounge Count: 0
---------------------
Label: Agitated

Example 3:
Average of features over normal days:
No prior stats available for this patient.
- **Age Group**: (80, 90]
- **Gender**: Female
---------------------
- **Physiological Data**:
- Body Temperature: 36.85
- Body weight: 55.3
- Diastolic blood pressure: 79.0
- Heart rate: 60.0
- O/E - muscle mass: 35.1
- Skin Temperature: 34.68
- Systolic blood pressure: 138.0
- Total body water: 47.1
---------------------
- **Activity Information**:
- Location Change Count: 107
- Time Spent Outside: 616.73 min
- Bathroom Count: 0
- Bedroom Count: 4
- Fridge Door Count: 36
- Hallway Count: 0
- Kitchen Count: 81
- Lounge Count: 0
---------------------
Label: Normal

Example 4:
Average of features over normal days:
- location_change_count: 293
- outside_time: 127
- Bathroom_count: 20
- Bedroom_count: 49
- Fridge Door_count: 49
- Hallway_count: 86
- Kitchen_count: 78
- Lounge_count: 85
---------------------
- **Age Group**: (70, 80]
- **Gender**: Male
---------------------
- **Physiological Data**:
- Body Temperature: 36.75
- Body weight: 84.9
- Diastolic blood pressure: 58.0
- Heart rate: 76.0
- O/E - muscle mass: 58.2
- Skin Temperature: 34.83
- Systolic blood pressure: 96.0
- Total body water: 49.4
---------------------
- **Activity Information**:
- Location Change Count: 259
- Time Spent Outside: 398.37 min
- Bathroom Count: 24
- Bedroom Count: 62
- Fridge Door Count: 32
- Hallway Count: 99
- Kitchen Count: 78
- Lounge Count: 54
---------------------
Label: Agitated

Example 5:
Average of features over normal days:
No prior stats available for this patient.
- **Age Group**: (90, 110]
- **Gender**: Male
---------------------
- **Physiological Data**:
- Body Temperature: 36.61
- Body weight: 69.9
- Diastolic blood pressure: 66.15
- Heart rate: 74.81
- O/E - muscle mass: 49.78
- Skin Temperature: 34.41
- Systolic blood pressure: 125.37
- Total body water: 50.65
---------------------
- **Activity Information**:
- Location Change Count: 99
- Time Spent Outside: 182.6 min
- Bathroom Count: 7
- Bedroom Count: 18
- Fridge Door Count: 14
- Hallway Count: 65
- Kitchen Count: 0
- Lounge Count: 46
---------------------
Label: Normal

Example 6:
Average of features over normal days:
- location_change_count: 198
- outside_time: 18
- Bathroom_count: 32
- Bedroom_count: 143
- Fridge Door_count: 17
- Hallway_count: 39
- Kitchen_count: 48
- Lounge_count: 63
---------------------
- **Age Group**: (80, 90]
- **Gender**: Female
---------------------
- **Physiological Data**:
- No physiological data available
---------------------
- **Activity Information**:
- Location Change Count: 298
- Time Spent Outside: 100.75 min
- Bathroom Count: 19
- Bedroom Count: 112
- Fridge Door Count: 30
- Hallway Count: 86
- Kitchen Count: 66
- Lounge Count: 113
---------------------
Label: Agitated

Example 7:
Average of features over normal days:
- location_change_count: 238
- outside_time: 31
- Bathroom_count: 53
- Bedroom_count: 51
- Fridge Door_count: 62
- Hallway_count: 54
- Kitchen_count: 90
- Lounge_count: 40
---------------------
- **Age Group**: (90, 110]
- **Gender**: Male
---------------------
- **Physiological Data**:
- Body Temperature: 36.13
- Body weight: 70.12
- Diastolic blood pressure: 68.0
- Heart rate: 81.0
- O/E - muscle mass: 47.54
- Skin Temperature: 34.15
- Systolic blood pressure: 100.0
- Total body water: 50.03
---------------------
- **Activity Information**:
- Location Change Count: 192
- Time Spent Outside: 4.07 min
- Bathroom Count: 54
- Bedroom Count: 51
- Fridge Door Count: 58
- Hallway Count: 29
- Kitchen Count: 74
- Lounge Count: 33
---------------------
Label: Normal

Example 8:
Average of features over normal days:
- location_change_count: 250
- outside_time: 17
- Bathroom_count: 76
- Bedroom_count: 14
- Fridge Door_count: 0
- Hallway_count: 104
- Kitchen_count: 117
- Lounge_count: 0
---------------------
- **Age Group**: (80, 90]
- **Gender**: Male
---------------------
- **Physiological Data**:
- No physiological data available
---------------------
- **Activity Information**:
- Location Change Count: 429
- Time Spent Outside: 5.2 min
- Bathroom Count: 108
- Bedroom Count: 95
- Fridge Door Count: 0
- Hallway Count: 152
- Kitchen Count: 133
- Lounge Count: 0
---------------------
Label: Agitated

Example 9:
Average of features over normal days:
No prior stats available for this patient.
- **Age Group**: (80, 90]
- **Gender**: Male
---------------------
- **Physiological Data**:
- Body Temperature: 36.67
- Body weight: 67.8
- Diastolic blood pressure: 65.0
- Heart rate: 74.0
- O/E - muscle mass: 49.9
- Skin Temperature: 34.15
- Systolic blood pressure: 124.0
- Total body water: 53.3
---------------------
- **Activity Information**:
- Location Change Count: 164
- Time Spent Outside: 113.25 min
- Bathroom Count: 0
- Bedroom Count: 35
- Fridge Door Count: 36
- Hallway Count: 53
- Kitchen Count: 76
- Lounge Count: 44
---------------------
Label: Normal

Question: What is the label for the following input based on the observed examples?[Agitated/Normal]
Average of features over normal days:
- location_change_count: 276
- outside_time: 24
- Bathroom_count: 20
- Bedroom_count: 51
- Fridge Door_count: 60
- Hallway_count: 65
- Kitchen_count: 75
- Lounge_count: 164
---------------------
- **Age Group**: (90, 110]
- **Gender**: Male
---------------------
- **Physiological Data**:
- Body Temperature: 36.02
- Body weight: 66.1
- Diastolic blood pressure: 84.0
- Heart rate: 94.0
- O/E - muscle mass: 47.46
- Skin Temperature: 34.15
- Systolic blood pressure: 132.0
- Total body water: 53.0
---------------------
- **Activity Information**:
- Location Change Count: 415
- Time Spent Outside: 4.13 min
- Bathroom Count: 19
- Bedroom Count: 53
- Fridge Door Count: 108
- Hallway Count: 85
- Kitchen Count: 135
- Lounge Count: 166
---------------------
Label: [MASK]

In [47]:
indexes = [i for i, val in enumerate(test_labels) if val == 'Normal']
print(indexes)

[1, 2, 6, 8, 9, 10, 13, 15, 17, 18]

OLMoE is a Fully open-source model, with open-source weights, datasets, checkpoints, and codes.

In [23]:
# Load OLMoE model
from transformers import AutoModelForCausalLM, AutoTokenizer
import torch

model_id = "allenai/OLMoE-1B-7B-0125"

tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModelForCausalLM.from_pretrained(
    model_id,
    device_map="auto",             # Optional: to place on correct device
    load_in_8bit=True              # or use `load_in_4bit=True` for more compression
)

tokenizer_config.json:   0%|          | 0.00/5.40k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/3.57M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/293 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/813 [00:00<?, ?B/s]

The `load_in_4bit` and `load_in_8bit` arguments are deprecated and will be removed in the future versions. Please, pass a `BitsAndBytesConfig` object in `quantization_config` argument instead.

model.safetensors.index.json:   0%|          | 0.00/287k [00:00<?, ?B/s]

Fetching 6 files:   0%|          | 0/6 [00:00<?, ?it/s]

model-00005-of-00006.safetensors:   0%|          | 0.00/4.99G [00:00<?, ?B/s]

model-00004-of-00006.safetensors:   0%|          | 0.00/4.99G [00:00<?, ?B/s]

model-00006-of-00006.safetensors:   0%|          | 0.00/2.71G [00:00<?, ?B/s]

model-00002-of-00006.safetensors:   0%|          | 0.00/4.99G [00:00<?, ?B/s]

model-00001-of-00006.safetensors:   0%|          | 0.00/4.99G [00:00<?, ?B/s]

model-00003-of-00006.safetensors:   0%|          | 0.00/4.99G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/6 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/115 [00:00<?, ?B/s]

In [51]:
inputs = tokenizer(few_shot_prompt, return_tensors="pt").to(model.device)
#print(tokenizer.decode(outputs[0], skip_special_tokens=True))

out = model.generate(
    **inputs,
    max_new_tokens=5,
    top_p=1,              # Or use nucleus sampling
    temperature=0.7,         # Controls randomness
    repetition_penalty=1.2,  # Penalize repetition
)
print(tokenizer.decode(out[0]))

Instruction: First, consider the provided context information. Then, observe and learn from the provided examples. Finally predict the label in the question part

Context: Agitation is a state of heightened restlessness or emotional disturbance that can affect both the mind and body. Individuals experiencing agitation may exhibit physical signs such as fidgeting, pacing, or rapid movements. Behaviorally, they might struggle to concentrate, become easily irritable, or engage in excessive talking. Emotionally, agitation often manifests as a feeling of tension or unease, sometimes escalating into hostility or aggression if not addressed. This condition can arise due to various triggers, including stress, anxiety, medical conditions, or external situations. Recognizing and addressing the underlying cause is essential for managing agitation effectively and preventing its escalation.

Example 0:
Average of features over normal days:
- location_change_count: 219
- outside_time: 133
- Bathroom_count: 19
- Bedroom_count: 33
- Fridge Door_count: 43
- Hallway_count: 51
- Kitchen_count: 108
- Lounge_count: 88
---------------------
- **Age Group**: (80, 90]
- **Gender**: Female
---------------------
- **Physiological Data**:
- Body Temperature: 36.4
- Body weight: 74.37
- Diastolic blood pressure: 80.0
- Heart rate: 130.0
- O/E - muscle mass: 40.93
- Skin Temperature: 34.15
- Systolic blood pressure: 177.0
- Total body water: 41.46
---------------------
- **Activity Information**:
- Location Change Count: 517
- Time Spent Outside: 5.03 min
- Bathroom Count: 1
- Bedroom Count: 8
- Fridge Door Count: 70
- Hallway Count: 188
- Kitchen Count: 199
- Lounge Count: 186
---------------------
Label: Agitated

Example 1:
Average of features over normal days:
- location_change_count: 175
- outside_time: 137
- Bathroom_count: 21
- Bedroom_count: 24
- Fridge Door_count: 31
- Hallway_count: 50
- Kitchen_count: 87
- Lounge_count: 39
---------------------
- **Age Group**: (80, 90]
- **Gender**: Male
---------------------
- **Physiological Data**:
- Body Temperature: 36.96
- Body weight: 72.7
- Diastolic blood pressure: 89.0
- Heart rate: 93.0
- O/E - muscle mass: 54.2
- Skin Temperature: 34.15
- Systolic blood pressure: 146.0
- Total body water: 52.3
---------------------
- **Activity Information**:
- Location Change Count: 259
- Time Spent Outside: 80.63 min
- Bathroom Count: 24
- Bedroom Count: 27
- Fridge Door Count: 48
- Hallway Count: 66
- Kitchen Count: 132
- Lounge Count: 52
---------------------
Label: Normal

Example 2:
Average of features over normal days:
- location_change_count: 250
- outside_time: 17
- Bathroom_count: 76
- Bedroom_count: 14
- Fridge Door_count: 0
- Hallway_count: 104
- Kitchen_count: 117
- Lounge_count: 0
---------------------
- **Age Group**: (80, 90]
- **Gender**: Male
---------------------
- **Physiological Data**:
- No physiological data available
---------------------
- **Activity Information**:
- Location Change Count: 420
- Time Spent Outside: 2.4 min
- Bathroom Count: 137
- Bedroom Count: 76
- Fridge Door Count: 0
- Hallway Count: 152
- Kitchen Count: 172
- Lounge Count: 0
---------------------
Label: Agitated

Example 3:
Average of features over normal days:
No prior stats available for this patient.
- **Age Group**: (80, 90]
- **Gender**: Female
---------------------
- **Physiological Data**:
- Body Temperature: 36.85
- Body weight: 55.3
- Diastolic blood pressure: 79.0
- Heart rate: 60.0
- O/E - muscle mass: 35.1
- Skin Temperature: 34.68
- Systolic blood pressure: 138.0
- Total body water: 47.1
---------------------
- **Activity Information**:
- Location Change Count: 107
- Time Spent Outside: 616.73 min
- Bathroom Count: 0
- Bedroom Count: 4
- Fridge Door Count: 36
- Hallway Count: 0
- Kitchen Count: 81
- Lounge Count: 0
---------------------
Label: Normal

Example 4:
Average of features over normal days:
- location_change_count: 293
- outside_time: 127
- Bathroom_count: 20
- Bedroom_count: 49
- Fridge Door_count: 49
- Hallway_count: 86
- Kitchen_count: 78
- Lounge_count: 85
---------------------
- **Age Group**: (70, 80]
- **Gender**: Male
---------------------
- **Physiological Data**:
- Body Temperature: 36.75
- Body weight: 84.9
- Diastolic blood pressure: 58.0
- Heart rate: 76.0
- O/E - muscle mass: 58.2
- Skin Temperature: 34.83
- Systolic blood pressure: 96.0
- Total body water: 49.4
---------------------
- **Activity Information**:
- Location Change Count: 259
- Time Spent Outside: 398.37 min
- Bathroom Count: 24
- Bedroom Count: 62
- Fridge Door Count: 32
- Hallway Count: 99
- Kitchen Count: 78
- Lounge Count: 54
---------------------
Label: Agitated

Example 5:
Average of features over normal days:
No prior stats available for this patient.
- **Age Group**: (90, 110]
- **Gender**: Male
---------------------
- **Physiological Data**:
- Body Temperature: 36.61
- Body weight: 69.9
- Diastolic blood pressure: 66.15
- Heart rate: 74.81
- O/E - muscle mass: 49.78
- Skin Temperature: 34.41
- Systolic blood pressure: 125.37
- Total body water: 50.65
---------------------
- **Activity Information**:
- Location Change Count: 99
- Time Spent Outside: 182.6 min
- Bathroom Count: 7
- Bedroom Count: 18
- Fridge Door Count: 14
- Hallway Count: 65
- Kitchen Count: 0
- Lounge Count: 46
---------------------
Label: Normal

Example 6:
Average of features over normal days:
- location_change_count: 198
- outside_time: 18
- Bathroom_count: 32
- Bedroom_count: 143
- Fridge Door_count: 17
- Hallway_count: 39
- Kitchen_count: 48
- Lounge_count: 63
---------------------
- **Age Group**: (80, 90]
- **Gender**: Female
---------------------
- **Physiological Data**:
- No physiological data available
---------------------
- **Activity Information**:
- Location Change Count: 298
- Time Spent Outside: 100.75 min
- Bathroom Count: 19
- Bedroom Count: 112
- Fridge Door Count: 30
- Hallway Count: 86
- Kitchen Count: 66
- Lounge Count: 113
---------------------
Label: Agitated

Example 7:
Average of features over normal days:
- location_change_count: 238
- outside_time: 31
- Bathroom_count: 53
- Bedroom_count: 51
- Fridge Door_count: 62
- Hallway_count: 54
- Kitchen_count: 90
- Lounge_count: 40
---------------------
- **Age Group**: (90, 110]
- **Gender**: Male
---------------------
- **Physiological Data**:
- Body Temperature: 36.13
- Body weight: 70.12
- Diastolic blood pressure: 68.0
- Heart rate: 81.0
- O/E - muscle mass: 47.54
- Skin Temperature: 34.15
- Systolic blood pressure: 100.0
- Total body water: 50.03
---------------------
- **Activity Information**:
- Location Change Count: 192
- Time Spent Outside: 4.07 min
- Bathroom Count: 54
- Bedroom Count: 51
- Fridge Door Count: 58
- Hallway Count: 29
- Kitchen Count: 74
- Lounge Count: 33
---------------------
Label: Normal

Example 8:
Average of features over normal days:
- location_change_count: 250
- outside_time: 17
- Bathroom_count: 76
- Bedroom_count: 14
- Fridge Door_count: 0
- Hallway_count: 104
- Kitchen_count: 117
- Lounge_count: 0
---------------------
- **Age Group**: (80, 90]
- **Gender**: Male
---------------------
- **Physiological Data**:
- No physiological data available
---------------------
- **Activity Information**:
- Location Change Count: 429
- Time Spent Outside: 5.2 min
- Bathroom Count: 108
- Bedroom Count: 95
- Fridge Door Count: 0
- Hallway Count: 152
- Kitchen Count: 133
- Lounge Count: 0
---------------------
Label: Agitated

Example 9:
Average of features over normal days:
No prior stats available for this patient.
- **Age Group**: (80, 90]
- **Gender**: Male
---------------------
- **Physiological Data**:
- Body Temperature: 36.67
- Body weight: 67.8
- Diastolic blood pressure: 65.0
- Heart rate: 74.0
- O/E - muscle mass: 49.9
- Skin Temperature: 34.15
- Systolic blood pressure: 124.0
- Total body water: 53.3
---------------------
- **Activity Information**:
- Location Change Count: 164
- Time Spent Outside: 113.25 min
- Bathroom Count: 0
- Bedroom Count: 35
- Fridge Door Count: 36
- Hallway Count: 53
- Kitchen Count: 76
- Lounge Count: 44
---------------------
Label: Normal

Example 10:
Average of features over normal days:
- location_change_count: 510
- outside_time: 112
- Bathroom_count: 41
- Bedroom_count: 37
- Fridge Door_count: 51
- Hallway_count: 176
- Kitchen_count: 121
- Lounge_count: 172
---------------------
- **Age Group**: (70, 80]
- **Gender**: Male
---------------------
- **Physiological Data**:
- Body Temperature: 36.06
- Body weight: 84.4
- Diastolic blood pressure: 76.13
- Heart rate: 64.75
- O/E - muscle mass: 53.81
- Skin Temperature: 34.15
- Systolic blood pressure: 130.47
- Total body water: 45.84
---------------------
- **Activity Information**:
- Location Change Count: 499
- Time Spent Outside: 32.63 min
- Bathroom Count: 39
- Bedroom Count: 36
- Fridge Door Count: 36
- Hallway Count: 179
- Kitchen Count: 133
- Lounge Count: 201
---------------------
Label: Agitated

Example 11:
Average of features over normal days:
No prior stats available for this patient.
- **Age Group**: (70, 80]
- **Gender**: Female
---------------------
- **Physiological Data**:
- Body Temperature: 35.34
- Body weight: 63.2
- Diastolic blood pressure: 92.0
- Heart rate: 78.0
- O/E - muscle mass: 46.2
- Skin Temperature: 31.48
- Systolic blood pressure: 147.0
- Total body water: 52.5
---------------------
- **Activity Information**:
- Location Change Count: 234
- Time Spent Outside: 1.9 min
- Bathroom Count: 25
- Bedroom Count: 39
- Fridge Door Count: 52
- Hallway Count: 56
- Kitchen Count: 37
- Lounge Count: 138
---------------------
Label: Normal

Example 12:
Average of features over normal days:
- location_change_count: 312
- outside_time: 6
- Bathroom_count: 49
- Bedroom_count: 39
- Fridge Door_count: 31
- Hallway_count: 123
- Kitchen_count: 70
- Lounge_count: 73
---------------------
- **Age Group**: (80, 90]
- **Gender**: Male
---------------------
- **Physiological Data**:
- Body Temperature: 36.36
- Body weight: 91.1
- Diastolic blood pressure: 68.0
- Heart rate: 71.0
- O/E - muscle mass: 61.8
- Skin Temperature: 34.1
- Systolic blood pressure: 118.0
- Total body water: 48.5
---------------------
- **Activity Information**:
- Location Change Count: 339
- Time Spent Outside: 17.58 min
- Bathroom Count: 58
- Bedroom Count: 42
- Fridge Door Count: 32
- Hallway Count: 125
- Kitchen Count: 70
- Lounge Count: 86
---------------------
Label: Agitated

Example 13:
Average of features over normal days:
- location_change_count: 263
- outside_time: 16
- Bathroom_count: 34
- Bedroom_count: 53
- Fridge Door_count: 47
- Hallway_count: 89
- Kitchen_count: 84
- Lounge_count: 57
---------------------
- **Age Group**: (90, 110]
- **Gender**: Female
---------------------
- **Physiological Data**:
- No physiological data available
---------------------
- **Activity Information**:
- Location Change Count: 305
- Time Spent Outside: 4.23 min
- Bathroom Count: 24
- Bedroom Count: 46
- Fridge Door Count: 44
- Hallway Count: 109
- Kitchen Count: 102
- Lounge Count: 65
---------------------
Label: Normal

Question: What is the label for the following input based on the observed examples?[Agitated/Normal]
Average of features over normal days:
- location_change_count: 234
- outside_time: 232
- Bathroom_count: 27
- Bedroom_count: 28
- Fridge Door_count: 59
- Hallway_count: 67
- Kitchen_count: 82
- Lounge_count: 50
---------------------
- **Age Group**: (90, 110]
- **Gender**: Female
---------------------
- **Physiological Data**:
- Body Temperature: 36.16
- Body weight: 53.8
- Diastolic blood pressure: 71.0
- Heart rate: 78.0
- O/E - muscle mass: 36.9
- Skin Temperature: 34.15
- Systolic blood pressure: 132.0
- Total body water: 49.7
---------------------
- **Activity Information**:
- Location Change Count: 286
- Time Spent Outside: 278.25 min
- Bathroom Count: 44
- Bedroom Count: 37
- Fridge Door Count: 56
- Hallway Count: 77
- Kitchen Count: 78
- Lounge Count: 58
---------------------
Label: [MASK]<|endoftext|>

In [30]:
# No mean stats
gpt_50_1 = ['Normal','Normal','Normal','Agitated','Agitated','Normal','Normal','Normal','Normal','Normal','Normal','Normal','Agitated','Normal','Normal','Normal','Normal','Agitated','Normal','Agitated']

# No mean stats
copilot_50_1 = ['Normal', 'Agitated', 'Normal', 'Agitated', 'Normal', 'Agitated', 'Normal', 'Agitated', 'Agitated', 'Normal', 'Normal', 'Agitated', 'Agitated', 'Normal', 'Agitated', 'Agitated', 'Normal', 'Normal', 'Normal', 'Agitated']

#Added mean [Kept in all other experiments]
copilot_50_2 = ['Normal', 'Agitated', 'Agitated', 'Agitated', 'Normal', 'Agitated', 'Normal', 'Agitated', 'Agitated', 'Normal', 'Normal', 'Agitated', 'Agitated', 'Normal', 'Agitated', 'Agitated', 'Agitated', 'Normal', 'Normal', 'Agitated']

# at once
copilot_10_2 = ['Normal', 'Agitated', 'Normal', 'Agitated', 'Normal', 'Agitated', 'Normal', 'Agitated', 'Agitated','Normal', 'Normal', 'Agitated', 'Agitated', 'Normal', 'Agitated', 'Agitated', 'Normal', 'Normal', 'Normal', 'Agitated']

# gradual
copilot_10_2_grad_repeat = ['Normal', 'Agitated', 'Normal', 'Agitated', 'Normal', 'Agitated', 'Normal', 'Agitated', 'Agitated', 'Normal', 'Normal', 'Agitated', 'Agitated', 'Normal', 'Agitated', 'Agitated', 'Normal', 'Normal','Normal','Agitated']

# No reapeat gradual
copilot_10_2_grad = ['Normal', 'Agitated', 'Agitated', 'Agitated', 'Normal','Normal','Agitated', 'Agitated', 'Agitated', 'Normal', 'Normal', 'Agitated','Agitated','Agitated', 'Agitated', 'Agitated', 'Agitated', 'Normal', 'Normal', 'Agitated']

# OLMo
olmo32_10 = ["Agitated","Agitated","Normal","Agitated","Agitated","Agitated","Agitated",
    "Agitated","Agitated","Normal","Normal","Agitated","Agitated","Agitated","Agitated",
    "Agitated","Normal","Normal","Normal","Agitated"]

new_copilot = [    "Normal",    "Normal",    "Agitated",    "Agitated","Normal","Normal","Agitated",
    "Agitated","Normal","Normal","Normal","Agitated","Normal","Agitated","Agitated","Agitated","Agitated",
    "Normal","Normal","Agitated"]

In [ ]:
# Set the padding token
tokenizer.pad_token = tokenizer.eos_token

# Tokenize input text
input_text = few_shot_prompt
device = model.device
inputs = tokenizer(
    input_text,
    return_tensors="pt",
    padding=True,
).to(device)

# Generate text
with torch.no_grad():
    output = model.generate(
        inputs["input_ids"],
        attention_mask=inputs["attention_mask"],
        num_return_sequences=1,
        temperature=0.7,
        top_k=50,
        top_p=0.95,
        repetition_penalty=1.2,
        max_new_tokens=30,
    )


# Decode and print the generated text
generated_text = tokenizer.decode(output[0], skip_special_tokens=True)
print("Generated Text:", generated_text)
from transformers import AutoModelForCausalLM, AutoTokenizer
import torch
from huggingface_hub import login

# Authenticate with Hugging Face Hub (if needed)
# Replace 'your_huggingface_token' with your actual token
login("your_huggingface_token")

device = "cpu"  # Change to "cuda" if running on a GPU

# Load the TinyLlama model and tokenizer
model_name = "meta-llama/Llama-3.2-1B"
context_length = 128000

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name, torch_dtype=torch.float16, device_map=device)

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

KeyboardInterrupt:

In [31]:
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, confusion_matrix, roc_auc_score, precision_recall_curve, auc

def evaluate(y_pred,y_true):
    # Calculate Accuracy
    accuracy = accuracy_score(y_true, y_pred)

    # Calculate F1 Score
    f1 = f1_score(y_true, y_pred)

    # Calculate Precision
    precision = precision_score(y_true, y_pred)

    # Calculate Sensitivity (Recall)
    sensitivity = recall_score(y_true, y_pred)

    # Calculate Specificity
    tn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()
    specificity = tn / (tn + fp)

    # Calculate ROC AUC
    roc_auc = roc_auc_score(y_true, y_pred)

    # Calculate PR AUC
    precision_curve, recall_curve, _ = precision_recall_curve(y_true, y_pred)
    pr_auc = auc(recall_curve, precision_curve)

    return accuracy, f1, precision, sensitivity, specificity, roc_auc, pr_auc

y_pred = [1 if p=='Agitated' else 0 for p in new_copilot]
y_true = [1 if p=='Agitated' else 0 for p in test_labels]
accuracy, f1, precision, sensitivity, specificity, roc_auc, pr_auc = evaluate(y_pred,y_true)
print(f"Accuracy: {accuracy}")
print(f"F1 Score: {f1}")
print(f"Precision: {precision}")
print(f"Sensitivity (Recall): {sensitivity}")
print(f"Specificity: {specificity}")
print(f"ROC AUC: {roc_auc}")
print(f"PR AUC: {pr_auc}")

Accuracy: 0.6
F1 Score: 0.6
Precision: 0.6
Sensitivity (Recall): 0.6
Specificity: 0.6
ROC AUC: 0.6
PR AUC: 0.7

In [ ]:
count = 0
for s in test_labels:
  if s=='Agitated':
    count+=1
print(f"Positive test count: {count}")
print(f"Total test:{len(test_labels)}")

Positive test count: 10
Total test:20

In [ ]:
# Install necessary packages
#!pip install transformers torch

# Import required libraries
from transformers import GPT2Tokenizer, GPT2LMHeadModel
import torch

# Load GPT-2 tokenizer & model
model_name = "gpt2"  # You can change to "gpt2-medium" or "gpt2-large" if needed
tokenizer = GPT2Tokenizer.from_pretrained(model_name)
model = GPT2LMHeadModel.from_pretrained(model_name)

# Set model to evaluation mode
model.eval()

GPT2LMHeadModel(
  (transformer): GPT2Model(
    (wte): Embedding(50257, 768)
    (wpe): Embedding(1024, 768)
    (drop): Dropout(p=0.1, inplace=False)
    (h): ModuleList(
      (0-11): 12 x GPT2Block(
        (ln_1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (attn): GPT2Attention(
          (c_attn): Conv1D(nf=2304, nx=768)
          (c_proj): Conv1D(nf=768, nx=768)
          (attn_dropout): Dropout(p=0.1, inplace=False)
          (resid_dropout): Dropout(p=0.1, inplace=False)
        )
        (ln_2): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (mlp): GPT2MLP(
          (c_fc): Conv1D(nf=3072, nx=768)
          (c_proj): Conv1D(nf=768, nx=3072)
          (act): NewGELUActivation()
          (dropout): Dropout(p=0.1, inplace=False)
        )
      )
    )
    (ln_f): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
  )
  (lm_head): Linear(in_features=768, out_features=50257, bias=False)
)

In [ ]:


# Define expert knowledge text about agitation in dementia patients
expert_knowledge = """
Agitation is a common behavioral symptom in dementia patients, characterized by restlessness, excessive movement, verbal or physical aggression, repetitive actions, and irritability. It can be triggered by discomfort, confusion, environmental changes, pain, or physiological stress.

Physiological responses such as elevated heart rate, increased blood pressure, and temperature changes often accompany these episodes. Patients may exhibit:
- Increased movement or wandering, especially at night
- Frequent and repetitive location changes
- Higher frequency of opening doors, suggesting exit attempts
- More time spent in hallways or pacing

To detect agitation, we analyze patient activity and physiological measurements. Patterns of agitation-related behaviors can be derived from structured patient records, which include demographic data, physiological measurements, and activity sequences.

"""

# Tokenize the expert knowledge input
input_ids = tokenizer.encode(expert_knowledge, return_tensors="pt")

# Generate text output based on expert knowledge
with torch.no_grad():
    output_ids = model.generate(input_ids, max_new_tokens=50, pad_token_id=tokenizer.eos_token_id)

# Decode generated text
generated_text = tokenizer.decode(output_ids[0], skip_special_tokens=True)

# Print GPT-2 output
print("===== GPT-2 Processing Expert Knowledge =====")
print(generated_text)

===== GPT-2 Processing Expert Knowledge =====

Agitation is a common behavioral symptom in dementia patients, characterized by restlessness, excessive movement, verbal or physical aggression, repetitive actions, and irritability. It can be triggered by discomfort, confusion, environmental changes, pain, or physiological stress.

Physiological responses such as elevated heart rate, increased blood pressure, and temperature changes often accompany these episodes. Patients may exhibit:
- Increased movement or wandering, especially at night
- Frequent and repetitive location changes
- Higher frequency of opening doors, suggesting exit attempts
- More time spent in hallways or pacing

To detect agitation, we analyze patient activity and physiological measurements. Patterns of agitation-related behaviors can be derived from structured patient records, which include demographic data, physiological measurements, and activity sequences.


The clinical features of dementia are complex and vary from person to person. The most common symptoms of dementia are:

- Decreased appetite

- Increased thirst

- Increased appetite for food

- Increased thirst for water

In [ ]:
# Define the function to process train samples efficiently
def process_all_train_samples(train_samples, model, tokenizer, max_tokens=100):
    """
    Feeds all training samples into GPT-2 without printing intermediate outputs.
    Only shows progress updates.
    """
    num_samples = len(train_samples)

    for i, sample in enumerate(train_samples):
        if i % 5 == 0:  # Print progress every 5 samples
            print(f"Processing train sample {i+1}/{num_samples}...")

        # Tokenize input
        input_ids = tokenizer.encode(sample, return_tensors="pt")

        # Generate output (GPT-2 processes the sample)
        with torch.no_grad():
            model.generate(input_ids, max_new_tokens=max_tokens, pad_token_id=tokenizer.eos_token_id)

    print("\n===== Training Completed! All samples processed. =====")

# Run the function on all train samples
process_all_train_samples(train_samples, model, tokenizer)

Processing train sample 1/229...
Processing train sample 6/229...
Processing train sample 11/229...
Processing train sample 16/229...
Processing train sample 21/229...
Processing train sample 26/229...
Processing train sample 31/229...
Processing train sample 36/229...
Processing train sample 41/229...
Processing train sample 46/229...
Processing train sample 51/229...
Processing train sample 56/229...
Processing train sample 61/229...
Processing train sample 66/229...
Processing train sample 71/229...
Processing train sample 76/229...
Processing train sample 81/229...
Processing train sample 86/229...
Processing train sample 91/229...
Processing train sample 96/229...
Processing train sample 101/229...
Processing train sample 106/229...
Processing train sample 111/229...
Processing train sample 116/229...
Processing train sample 121/229...
Processing train sample 126/229...
Processing train sample 131/229...
Processing train sample 136/229...
Processing train sample 141/229...
Processing train sample 146/229...
Processing train sample 151/229...
Processing train sample 156/229...
Processing train sample 161/229...
Processing train sample 166/229...
Processing train sample 171/229...
Processing train sample 176/229...
Processing train sample 181/229...
Processing train sample 186/229...
Processing train sample 191/229...
Processing train sample 196/229...
Processing train sample 201/229...
Processing train sample 206/229...
Processing train sample 211/229...
Processing train sample 216/229...
Processing train sample 221/229...
Processing train sample 226/229...

===== Training Completed! All samples processed. =====

In [ ]:
import re
import torch

def generate_gpt2_prediction(prompt, max_length=250):
    """Generates GPT-2 output given a test sample prompt."""
    inputs = tokenizer(prompt, return_tensors="pt", truncation=True, max_length=512)
    with torch.no_grad():
        outputs = model.generate(**inputs, max_length=max_length, num_return_sequences=1)

    generated_text = tokenizer.decode(outputs[0], skip_special_tokens=True)

    return generated_text

def extract_predicted_label(generated_text):
    """Extracts the predicted label (Agitated/Normal) from GPT-2's generated response."""
    match = re.search(r'Label(?: \(Choose Agitated or Normal\))?:?\s*(Agitated|Normal)', generated_text, re.IGNORECASE)
    if match:
        return match.group(1).capitalize()  # Ensure consistent formatting
    return "Unknown"

# Modify test samples format to ensure GPT-2 understands the task better
test_samples = [sample.replace("Label: [MASK]",
    "Based on the above information, is the patient Agitated or Normal? Choose one.\nPrediction:")
    for sample in test_samples]

# Initialize counters
correct_predictions = 0
total_samples = len(test_samples)
predictions = []

print("\n===== Running GPT-2 on Test Samples =====")

for idx, (prompt, true_label) in enumerate(zip(test_samples, test_labels)):
    print(f"\n🔹 **Testing Sample {idx+1}/{total_samples}**")
    print("🚀 Feeding prompt to GPT-2...")

    # Generate GPT-2 prediction
    generated_text = generate_gpt2_prediction(prompt)

    # Extract predicted label
    predicted_label = extract_predicted_label(generated_text)
    predictions.append(predicted_label)

    # Compare with ground truth
    is_correct = predicted_label == true_label
    correct_predictions += int(is_correct)

    # Display result
    print(f"📝 **Predicted Label:** {predicted_label} | ✅ **True Label:** {true_label} {'✔' if is_correct else '❌'}")
    print("--------------------------------------------------")

# Compute accuracy
accuracy = (correct_predictions / total_samples) * 100
print(f"\n🎯 **Final Accuracy:** {accuracy:.2f}% ({correct_predictions}/{total_samples})")

# Display summary of predictions
print("\n===== Prediction Summary =====")
for i in range(total_samples):
    print(f"Test Sample {i+1}: Predicted={predictions[i]} | True={test_labels[i]}")

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

===== Running GPT-2 on Test Samples =====

🔹 **Testing Sample 1/20**
🚀 Feeding prompt to GPT-2...

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

📝 **Predicted Label:** Unknown | ✅ **True Label:** Agitated ❌
--------------------------------------------------

🔹 **Testing Sample 2/20**
🚀 Feeding prompt to GPT-2...

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

📝 **Predicted Label:** Unknown | ✅ **True Label:** Normal ❌
--------------------------------------------------

🔹 **Testing Sample 3/20**
🚀 Feeding prompt to GPT-2...

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

📝 **Predicted Label:** Unknown | ✅ **True Label:** Normal ❌
--------------------------------------------------

🔹 **Testing Sample 4/20**
🚀 Feeding prompt to GPT-2...

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

📝 **Predicted Label:** Unknown | ✅ **True Label:** Agitated ❌
--------------------------------------------------

🔹 **Testing Sample 5/20**
🚀 Feeding prompt to GPT-2...

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

📝 **Predicted Label:** Unknown | ✅ **True Label:** Agitated ❌
--------------------------------------------------

🔹 **Testing Sample 6/20**
🚀 Feeding prompt to GPT-2...

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

📝 **Predicted Label:** Unknown | ✅ **True Label:** Agitated ❌
--------------------------------------------------

🔹 **Testing Sample 7/20**
🚀 Feeding prompt to GPT-2...

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

📝 **Predicted Label:** Unknown | ✅ **True Label:** Normal ❌
--------------------------------------------------

🔹 **Testing Sample 8/20**
🚀 Feeding prompt to GPT-2...

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

📝 **Predicted Label:** Unknown | ✅ **True Label:** Agitated ❌
--------------------------------------------------

🔹 **Testing Sample 9/20**
🚀 Feeding prompt to GPT-2...

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

📝 **Predicted Label:** Unknown | ✅ **True Label:** Normal ❌
--------------------------------------------------

🔹 **Testing Sample 10/20**
🚀 Feeding prompt to GPT-2...

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

📝 **Predicted Label:** Unknown | ✅ **True Label:** Normal ❌
--------------------------------------------------

🔹 **Testing Sample 11/20**
🚀 Feeding prompt to GPT-2...

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

📝 **Predicted Label:** Unknown | ✅ **True Label:** Normal ❌
--------------------------------------------------

🔹 **Testing Sample 12/20**
🚀 Feeding prompt to GPT-2...

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

📝 **Predicted Label:** Unknown | ✅ **True Label:** Agitated ❌
--------------------------------------------------

🔹 **Testing Sample 13/20**
🚀 Feeding prompt to GPT-2...

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

📝 **Predicted Label:** Unknown | ✅ **True Label:** Agitated ❌
--------------------------------------------------

🔹 **Testing Sample 14/20**
🚀 Feeding prompt to GPT-2...

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

📝 **Predicted Label:** Unknown | ✅ **True Label:** Normal ❌
--------------------------------------------------

🔹 **Testing Sample 15/20**
🚀 Feeding prompt to GPT-2...

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

📝 **Predicted Label:** Unknown | ✅ **True Label:** Agitated ❌
--------------------------------------------------

🔹 **Testing Sample 16/20**
🚀 Feeding prompt to GPT-2...

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

📝 **Predicted Label:** Unknown | ✅ **True Label:** Normal ❌
--------------------------------------------------

🔹 **Testing Sample 17/20**
🚀 Feeding prompt to GPT-2...

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

📝 **Predicted Label:** Unknown | ✅ **True Label:** Agitated ❌
--------------------------------------------------

🔹 **Testing Sample 18/20**
🚀 Feeding prompt to GPT-2...

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

📝 **Predicted Label:** Unknown | ✅ **True Label:** Normal ❌
--------------------------------------------------

🔹 **Testing Sample 19/20**
🚀 Feeding prompt to GPT-2...

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

📝 **Predicted Label:** Unknown | ✅ **True Label:** Normal ❌
--------------------------------------------------

🔹 **Testing Sample 20/20**
🚀 Feeding prompt to GPT-2...
📝 **Predicted Label:** Unknown | ✅ **True Label:** Agitated ❌
--------------------------------------------------

🎯 **Final Accuracy:** 0.00% (0/20)

===== Prediction Summary =====
Test Sample 1: Predicted=Unknown | True=Agitated
Test Sample 2: Predicted=Unknown | True=Normal
Test Sample 3: Predicted=Unknown | True=Normal
Test Sample 4: Predicted=Unknown | True=Agitated
Test Sample 5: Predicted=Unknown | True=Agitated
Test Sample 6: Predicted=Unknown | True=Agitated
Test Sample 7: Predicted=Unknown | True=Normal
Test Sample 8: Predicted=Unknown | True=Agitated
Test Sample 9: Predicted=Unknown | True=Normal
Test Sample 10: Predicted=Unknown | True=Normal
Test Sample 11: Predicted=Unknown | True=Normal
Test Sample 12: Predicted=Unknown | True=Agitated
Test Sample 13: Predicted=Unknown | True=Agitated
Test Sample 14: Predicted=Unknown | True=Normal
Test Sample 15: Predicted=Unknown | True=Agitated
Test Sample 16: Predicted=Unknown | True=Normal
Test Sample 17: Predicted=Unknown | True=Agitated
Test Sample 18: Predicted=Unknown | True=Normal
Test Sample 19: Predicted=Unknown | True=Normal
Test Sample 20: Predicted=Unknown | True=Agitated

In [ ]:
pip install sacremoses

Collecting sacremoses
  Downloading sacremoses-0.1.1-py3-none-any.whl.metadata (8.3 kB)
Requirement already satisfied: regex in /usr/local/lib/python3.11/dist-packages (from sacremoses) (2024.11.6)
Requirement already satisfied: click in /usr/local/lib/python3.11/dist-packages (from sacremoses) (8.1.8)
Requirement already satisfied: joblib in /usr/local/lib/python3.11/dist-packages (from sacremoses) (1.4.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from sacremoses) (4.67.1)
Downloading sacremoses-0.1.1-py3-none-any.whl (897 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 897.5/897.5 kB 33.6 MB/s eta 0:00:00
Installing collected packages: sacremoses
Successfully installed sacremoses-0.1.1

In [ ]:
from transformers import AutoTokenizer, AutoModelForCausalLM

# Load BioGPT model
model_name = "microsoft/BioGPT-Large"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name)
print("✅ BioGPT loaded successfully!")

config.json:   0%|          | 0.00/658 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/6.29G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/137 [00:00<?, ?B/s]

✅ BioGPT loaded successfully!

In [ ]:
#!pip install transformers torch  # Install required libraries

#from transformers import AutoModelForCausalLM, AutoTokenizer
#import torch
import re

# Load BioGPT model & tokenizer
#model_name = "microsoft/BioGPT-Large"  # You can also try "microsoft/BioGPT"
#tokenizer = AutoTokenizer.from_pretrained(model_name)
#model = AutoModelForCausalLM.from_pretrained(model_name)
model.eval()  # Set to evaluation mode

# Function to generate BioGPT responses
def generate_biogpt_prediction(prompt, max_length=250):
    """Generates BioGPT output given a text prompt."""
    inputs = tokenizer(prompt, return_tensors="pt", truncation=True, max_length=512)
    with torch.no_grad():
        outputs = model.generate(**inputs, max_length=max_length, num_return_sequences=1)

    generated_text = tokenizer.decode(outputs[0], skip_special_tokens=True)
    return generated_text

In [ ]:
expert_knowledge_prompt = """
Agitation in dementia patients is characterized by abnormal behavioral patterns such as increased movement, restlessness, repetitive actions, and disrupted routines.
Key physiological indicators of agitation include:
- Elevated heart rate and irregular heart rate variability
- Increased blood pressure, especially systolic pressure
- Fluctuations in body temperature
- Frequent and erratic movements between rooms or outdoor areas
- Increased interactions with kitchen appliances, doors, and hallways
- Changes in sleep-wake cycles, often leading to nighttime activity increases

Understanding these patterns allows us to classify patient states. Based on the provided physiological and activity data, determine whether the patient is in an "Agitated" or "Normal" state.
"""

print("\n===== 🩺 Prompting BioGPT with Expert Knowledge on Agitation =====")
expert_response = generate_biogpt_prediction(expert_knowledge_prompt)
print("📝 BioGPT Response:\n", expert_response)

===== 🩺 Prompting BioGPT with Expert Knowledge on Agitation =====
📝 BioGPT Response:
 Agitation in dementia patients is characterized by abnormal behavioral patterns such as increased movement, restlessness, repetitive actions, and disrupted routines. Key physiological indicators of agitation include: - Elevated heart rate and irregular heart rate variability - Increased blood pressure, especially systolic pressure - Fluctuations in body temperature - Frequent and erratic movements between rooms or outdoor areas - Increased interactions with kitchen appliances, doors, and hallways - Changes in sleep-wake cycles, often leading to nighttime activity increases Understanding these patterns allows us to classify patient states. Based on the provided physiological and activity data, determine whether the patient is in an "Agitated" or "Normal" state. This paper describes a system that uses a wearable sensor to collect physiological and activity data from dementia patients. The system is designed to be used in a home environment and is able to collect data from multiple sensors placed on the patient's body. The collected data is then used to classify the patient's state. The system is able to classify the patient's state with an accuracy of 9 0%. < / FREETEXT > < / ABSTRACT > ▃

In [ ]:
import random
from tqdm import tqdm  # Import progress bar

# Shuffle training samples before feeding them to BioGPT
random.shuffle(train_samples)

print("\n===== 🚀 Feeding BioGPT All Training Samples (Tracking Progress) =====")

for idx, train_sample in enumerate(tqdm(train_samples, desc="Processing Train Samples")):
    # Generate response silently without printing (helps build context)
    _ = generate_biogpt_prediction(train_sample)

print("\n✅ Done! BioGPT has processed all training samples.\n")

===== 🚀 Feeding BioGPT All Training Samples (Tracking Progress) =====

Processing Train Samples: 100%|██████████| 229/229 [1:06:37<00:00, 17.46s/it]

✅ Done! BioGPT has processed all training samples.

In [ ]:
def extract_predicted_label(generated_text):
    """Extracts the predicted label (Agitated/Normal) from BioGPT's response."""
    match = re.search(r'(Agitated|Normal)', generated_text, re.IGNORECASE)
    if match:
        return match.group(1).capitalize()  # Standardize output format
    return "Unknown"

correct_predictions = 0
total_samples = len(test_samples)
predictions = []

print("\n===== 🩺 Testing BioGPT on Unlabeled Test Samples =====")

for idx, (test_sample, true_label) in enumerate(zip(test_samples, test_labels)):
    print(f"\n🔹 **Testing Sample {idx+1}/{total_samples}**")
    print("🚀 Feeding test sample to BioGPT...")

    # Generate prediction
    generated_text = generate_biogpt_prediction(test_sample)

    # Extract label
    predicted_label = extract_predicted_label(generated_text)
    predictions.append(predicted_label)

    # Compare with ground truth
    is_correct = predicted_label == true_label
    correct_predictions += int(is_correct)

    # Print result
    print(f"📝 **Predicted Label:** {predicted_label} | ✅ **True Label:** {true_label} {'✔' if is_correct else '❌'}")
    print("--------------------------------------------------")

# Compute accuracy
accuracy = (correct_predictions / total_samples) * 100
print(f"\n🎯 **Final Accuracy:** {accuracy:.2f}% ({correct_predictions}/{total_samples})")

# Display summary
print("\n===== Prediction Summary =====")
for i in range(total_samples):
    print(f"Test Sample {i+1}: Predicted={predictions[i]} | True={test_labels[i]}")

===== 🩺 Testing BioGPT on Unlabeled Test Samples =====

🔹 **Testing Sample 1/20**
🚀 Feeding test sample to BioGPT...
📝 **Predicted Label:** Unknown | ✅ **True Label:** Agitated ❌
--------------------------------------------------

🔹 **Testing Sample 2/20**
🚀 Feeding test sample to BioGPT...
📝 **Predicted Label:** Unknown | ✅ **True Label:** Normal ❌
--------------------------------------------------

🔹 **Testing Sample 3/20**
🚀 Feeding test sample to BioGPT...
📝 **Predicted Label:** Unknown | ✅ **True Label:** Normal ❌
--------------------------------------------------

🔹 **Testing Sample 4/20**
🚀 Feeding test sample to BioGPT...
📝 **Predicted Label:** Unknown | ✅ **True Label:** Agitated ❌
--------------------------------------------------

🔹 **Testing Sample 5/20**
🚀 Feeding test sample to BioGPT...
📝 **Predicted Label:** Unknown | ✅ **True Label:** Agitated ❌
--------------------------------------------------

🔹 **Testing Sample 6/20**
🚀 Feeding test sample to BioGPT...
📝 **Predicted Label:** Unknown | ✅ **True Label:** Agitated ❌
--------------------------------------------------

🔹 **Testing Sample 7/20**
🚀 Feeding test sample to BioGPT...
📝 **Predicted Label:** Unknown | ✅ **True Label:** Normal ❌
--------------------------------------------------

🔹 **Testing Sample 8/20**
🚀 Feeding test sample to BioGPT...
📝 **Predicted Label:** Unknown | ✅ **True Label:** Agitated ❌
--------------------------------------------------

🔹 **Testing Sample 9/20**
🚀 Feeding test sample to BioGPT...
📝 **Predicted Label:** Unknown | ✅ **True Label:** Normal ❌
--------------------------------------------------

🔹 **Testing Sample 10/20**
🚀 Feeding test sample to BioGPT...
📝 **Predicted Label:** Unknown | ✅ **True Label:** Normal ❌
--------------------------------------------------

🔹 **Testing Sample 11/20**
🚀 Feeding test sample to BioGPT...
📝 **Predicted Label:** Unknown | ✅ **True Label:** Normal ❌
--------------------------------------------------

🔹 **Testing Sample 12/20**
🚀 Feeding test sample to BioGPT...
📝 **Predicted Label:** Unknown | ✅ **True Label:** Agitated ❌
--------------------------------------------------

🔹 **Testing Sample 13/20**
🚀 Feeding test sample to BioGPT...
📝 **Predicted Label:** Unknown | ✅ **True Label:** Agitated ❌
--------------------------------------------------

🔹 **Testing Sample 14/20**
🚀 Feeding test sample to BioGPT...
📝 **Predicted Label:** Unknown | ✅ **True Label:** Normal ❌
--------------------------------------------------

🔹 **Testing Sample 15/20**
🚀 Feeding test sample to BioGPT...
📝 **Predicted Label:** Unknown | ✅ **True Label:** Agitated ❌
--------------------------------------------------

🔹 **Testing Sample 16/20**
🚀 Feeding test sample to BioGPT...
📝 **Predicted Label:** Unknown | ✅ **True Label:** Normal ❌
--------------------------------------------------

🔹 **Testing Sample 17/20**
🚀 Feeding test sample to BioGPT...
📝 **Predicted Label:** Unknown | ✅ **True Label:** Agitated ❌
--------------------------------------------------

🔹 **Testing Sample 18/20**
🚀 Feeding test sample to BioGPT...
📝 **Predicted Label:** Unknown | ✅ **True Label:** Normal ❌
--------------------------------------------------

🔹 **Testing Sample 19/20**
🚀 Feeding test sample to BioGPT...
📝 **Predicted Label:** Unknown | ✅ **True Label:** Normal ❌
--------------------------------------------------

🔹 **Testing Sample 20/20**
🚀 Feeding test sample to BioGPT...
📝 **Predicted Label:** Unknown | ✅ **True Label:** Agitated ❌
--------------------------------------------------

🎯 **Final Accuracy:** 0.00% (0/20)

===== Prediction Summary =====
Test Sample 1: Predicted=Unknown | True=Agitated
Test Sample 2: Predicted=Unknown | True=Normal
Test Sample 3: Predicted=Unknown | True=Normal
Test Sample 4: Predicted=Unknown | True=Agitated
Test Sample 5: Predicted=Unknown | True=Agitated
Test Sample 6: Predicted=Unknown | True=Agitated
Test Sample 7: Predicted=Unknown | True=Normal
Test Sample 8: Predicted=Unknown | True=Agitated
Test Sample 9: Predicted=Unknown | True=Normal
Test Sample 10: Predicted=Unknown | True=Normal
Test Sample 11: Predicted=Unknown | True=Normal
Test Sample 12: Predicted=Unknown | True=Agitated
Test Sample 13: Predicted=Unknown | True=Agitated
Test Sample 14: Predicted=Unknown | True=Normal
Test Sample 15: Predicted=Unknown | True=Agitated
Test Sample 16: Predicted=Unknown | True=Normal
Test Sample 17: Predicted=Unknown | True=Agitated
Test Sample 18: Predicted=Unknown | True=Normal
Test Sample 19: Predicted=Unknown | True=Normal
Test Sample 20: Predicted=Unknown | True=Agitated